# -*- coding: utf-8 -*-
{
    'name': 'AF HR - Module',
    'version': '1.0.0',
    'category': 'hr',
    'author': 'Abderrahmane Guessoum - Alpha Brains Technologies',
    'website': 'www.fiverr.com/aabcrow',
    'depends': [
        'hr',
        'hr_contract',
        'hr_attendance',
        'hr_holidays',
        'hr_payroll',
        'report_xlsx',
    ],
    'data': [
        'security/ir.model.access.csv',
        'views/hr_employee_views.xml',
        'views/hr_contract_views.xml',
        'views/hr_leave_views.xml',
        'views/regenerate_work_entries_view.xml',
        'views/hr_monthly_accrual.xml',
        'report/hr_employee_info_report.xml',
        'report/hr_employee_info_template.xml',
        'report/hr_payslip_run_template.xml',
    ],
    'installable': True,
    'auto_install': False,
    'application': False,
    'license': 'LGPL-3',
}
